### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by nodegraphics** [Tugcga/S-USD#1]
Hello,
I've tried to install the USD plugin to Workgroup folder but i couldn't get it working,. 
I've installed Pyton 2.7.16 version.

```
# ERROR : Traceback (most recent call last):
#   File "<Script Block 2>", line 13, in <module>
#     import export_processor
#   File "C:\WORKGROUP_2015\Application\Plugins\export_processor.py", line 2, in <module>
#     from pxr import Usd, UsdGeom
# ImportError: No module named pxr
#  - [line 13 in C:\WORKGROUP_2015\Application\Plugins\USDExportPlugin.py]
# ERROR : Traceback (most recent call last):
#   File "<Script Block 2>", line 13, in <module>
#     import import_processor
#   File "C:\WORKGROUP_2015\Application\Plugins\import_processor.py", line 2, in <module>
#     from pxr import Usd, UsdGeom
# ImportError: No module named pxr
#  - [line 13 in C:\WORKGROUP_2015\Application\Plugins\USDImportPlugin.py]
# ERROR : Traceback (most recent call last):
#   File "<Script Block 2>", line 13, in <module>
#     import utils
#   File "C:\WORKGROUP_2015\Application\Plugins\utils.py", line 1, in <module>
#     from pxr import UsdGeom, Gf
# ImportError: No module named pxr
#  - [line 13 in C:\WORKGROUP_2015\Application\Plugins\USDOperatorsPlugin.py]
```

<img width="368" alt="Screenshot - 2023-02-13 19 48 15" src="https://user-images.githubusercontent.com/10071439/218634477-5675a697-462f-4bb9-a24a-9c1c47167eac.png">

**Comment by Tugcga** [comment]
It requires additional libraries. [Here](https://ssoftadd.github.io/usdPage.html) is described how to install it.

**Comment by nodegraphics** [comment]
awesome,
Thank you
